### ISSUE TITLE
Previous transaction issue

### ISSUE THREAD

**Issue by Gbanks2230** [rio-org/validator-ejector#3]
Incomplete previous transaction not allowing new transactions to be carried out. 
The incomplete transaction as already been confirmed as a completed transaction on the blockchain but it still shows incomplete on RIO network and this is stoping me from creating new transactions ![image](https://github.com/rio-org/validator-ejector/assets/138335119/a8503c2e-a70a-4433-9b06-840ce3cf4749)

Please look into this or give hints on how to fix it

**Comment by solimander** [comment]
@Gbanks2230 The Goerli testnet has been deprecated. A Holesky testnet instance will be live in the next couple days. Thanks!

**Comment by Gbanks2230** [comment]
Thank you it is fixed now
